# sfPropelPlanetPlugin configuration
# This file will be parsed and the values below will be set. If you want to 
# override them, just edit your own application/project app.yml file setting
# the properties you want to override, eg.
# 
#    // file apps/frontend/config/app.yml
#    all:
#      planet:
#        title:       Les flux de mes amis
#        homepage:    http://monblog.net/planet
#        description: Ils sont tous sympathiques
#        language:    fr
all:
  planet:

    # Planet metadata
    title:            My Planet               # The title of your planet
    homepage:         "http://myplanet.foo/"  # The url of the homepage of your website/planet
    description:      The planet I live on    # A short description of your planet
    language:         en-us                   # The main language of aggregated entries
    editor_email:     ~                       # The editor email address
    webmaster_email:  ~                       # The webmaster email address
    
    # Advanced configuration
    display_feeds_list: true   # displays the list of the active feeds on every page
    max_per_page:       10     # sets max entries per page
    routes_register:    true   # provides native routes for the sfPlanet web module
    xss_paranoid:       false  # set to true if you don't want html displayed on your planet (less shiny, but useful for untrusted sources)           

    # Available periodicities, in seconds. This will fill the according admin selectboxes
    periodicity:
      60:    one minute
      300:   five minutes
      900:   fifteen minutes
      1800:  half an hour
      3600:  one hour
      7200:  two hours
      18000: five hours
      43200: half a day
      86400: one day